import { fileURLToPath } from 'node:url';
import type { PgDatabase, PgQueryResultHKT } from 'drizzle-orm/pg-core';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import * as schema from './schema/index.js';

export { schema };

/**
 * Any Drizzle PostgreSQL database bound to the Judge Copilot schema. Production uses
 * postgres.js; tests use in-process PGlite. Code that only needs to query should accept this.
 */
export type JudgeDatabase = PgDatabase<PgQueryResultHKT, typeof schema>;

/** Absolute path of the SQL migrations generated by drizzle-kit. */
export const migrationsFolder = fileURLToPath(new URL('../drizzle', import.meta.url));

export interface DatabaseConnection {
  db: JudgeDatabase;
  close: () => Promise<void>;
}

/**
 * Opens a PostgreSQL connection pool. Nothing in M0 connects at import or boot time; a
 * connection exists only when a caller explicitly invokes this.
 */
export function createDatabase(
  databaseUrl: string,
  options: { maxConnections?: number } = {},
): DatabaseConnection {
  const client = postgres(databaseUrl, { max: options.maxConnections ?? 10 });
  return {
    db: drizzle(client, { schema }),
    close: () => client.end(),
  };
}
